# Generated by Django 5.1.1 on 2024-09-23 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_token_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user_token',
        ),
        migrations.AddField(
            model_name='comments',
            name='user_token',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.token'),
            preserve_default=False,
        ),
    ]
